name: Aggregate Daily Rankings

on:
  schedule:
    - cron: '*/30 * * * *'  # 30分おき
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase-aggregator

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: node aggregate.js
        env:
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
          PERIODS: daily
